//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.Data.Postcodes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterPostcode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterPostcode()
        {
            this.DAS_PostcodeDisadvantage = new HashSet<DAS_PostcodeDisadvantage>();
            this.EFA_PostcodeAreaCost = new HashSet<EFA_PostcodeAreaCost>();
            this.EFA_PostcodeDisadvantage = new HashSet<EFA_PostcodeDisadvantage>();
            this.ONS_Postcodes = new HashSet<ONS_Postcodes>();
            this.SFA_PostcodeAreaCost = new HashSet<SFA_PostcodeAreaCost>();
            this.SFA_PostcodeDisadvantage = new HashSet<SFA_PostcodeDisadvantage>();
            this.HMPP_Postcodes = new HashSet<HMPP_Postcodes>();
        }
    
        public string Postcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAS_PostcodeDisadvantage> DAS_PostcodeDisadvantage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFA_PostcodeAreaCost> EFA_PostcodeAreaCost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFA_PostcodeDisadvantage> EFA_PostcodeDisadvantage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ONS_Postcodes> ONS_Postcodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFA_PostcodeAreaCost> SFA_PostcodeAreaCost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFA_PostcodeDisadvantage> SFA_PostcodeDisadvantage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HMPP_Postcodes> HMPP_Postcodes { get; set; }
    }
}
