//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.Data.Postcodes.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ESFA.DC.Data.Postcodes.Model.Interfaces;
    
    public partial class Postcodes : DbContext, IPostcodes
    {
        public Postcodes()
            : base("name=Postcodes")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CareerLearningPilot_Postcode> CareerLearningPilot_Postcode { get; set; }
        public virtual DbSet<DAS_PostcodeDisadvantage> DAS_PostcodeDisadvantage { get; set; }
        public virtual DbSet<EFA_PostcodeAreaCost> EFA_PostcodeAreaCost { get; set; }
        public virtual DbSet<EFA_PostcodeDisadvantage> EFA_PostcodeDisadvantage { get; set; }
        public virtual DbSet<MasterPostcode> MasterPostcodes { get; set; }
        public virtual DbSet<ONS_Postcodes> ONS_Postcodes { get; set; }
        public virtual DbSet<SFA_PostcodeAreaCost> SFA_PostcodeAreaCost { get; set; }
        public virtual DbSet<SFA_PostcodeDisadvantage> SFA_PostcodeDisadvantage { get; set; }
        public virtual DbSet<HMPP_Postcodes> HMPP_Postcodes { get; set; }
        public virtual DbSet<VersionInfo> VersionInfos { get; set; }
    }
}
