//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.Data.Postcodes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionInfo
    {
        public string DataSource { get; set; }
        public string VersionNumber { get; set; }
        public string Comments { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedAt { get; set; }
    }
}
